### ISSUE TITLE
Add custom soundfonts

### ISSUE THREAD

**Issue by j-funk** [danigb/soundfont-player#12]
Is it possible to add my own soundfonts?

**Comment by danigb** [comment]
Yes, in theory, but I've never tried. You had to pre-render them, thing that I've never done. You can take a look to: https://github.com/gleitz/midi-js-soundfonts

We can discuss the process here, if you want to try.

**Comment by j-funk** [comment]
I think this was what I was asking about 

https://github.com/danigb/soundfont-player/pull/6

Will continue to discuss there, thanks!
