### ISSUE TITLE
Note about using the library on iOS

### ISSUE THREAD

**Issue by mattbierner** [danigb/soundfont-player#17]
Just a quick note about using this library on iOS: I do not believe that the default ogg files are supported, but you can use the mp3 versions just fine:
 
```js
const loader = name =>
    'https://cdn.rawgit.com/gleitz/midi-js-Soundfonts/master/FluidR3_GM/' + name + '-mp3.js';

new Soundfont(ctx, loader);
```

It may be worth adding a note to the readme about this, or perhaps changing the default since I believe mp3 does have broader support:
http://caniuse.com/#feat=ogg-vorbis
http://caniuse.com/#feat=mp3

**Comment by danigb** [comment]
Thanks for the info! I'm not sure about what to do... a note to the readme sounds enough for me, but I'm open to change it by default. Opinions and PR are welcomed ;-)

**Comment by danigb** [comment]
Finally I added a note into README. Thanks a lot!
