### ISSUE TITLE
global soundfont.onready missing

### ISSUE THREAD

**Issue by frankbaele** [danigb/soundfont-player#20]
Hi, 

The documentation suggests there is a onready callback on soundfont level, but this function is missing from the library. The only onready i could find was on instrument level.

https://github.com/danigb/soundfont-player#soundfontonreadycallback
Weird thing is that this commit adds is: 8ac8296199628d5a2598536a7b6007b777a419e5

Maybe got lost in the merges?

**Comment by danigb** [comment]
Good catch! Yes, I don't know when or where we loosed that function! Thanks for the PR.
