### ISSUE TITLE
Plug-in MIDI API

### ISSUE THREAD

**Issue by McOmghall** [danigb/soundfont-player#24]
Is there any way I can throw data from the Web MIDI API into this library to play it? Any examples of this?

**Comment by danigb** [comment]
Hi Pedro,

It should be easy to connect to Web MIDI API since the returned player accepts midi notes directly:

```
var instrument = soundfont.instrument('acoustic_grand_piano')
instrument.onready(function() {
  instrument.play(69) // <= play A4
})
````

Anyway, I'm afraid currently there's no example of this. PR are welcomed ;-)

Un saludo

**Comment by McOmghall** [comment]
It could be better if you just parsed/create the 3 byte standard MIDI messages in the library instead of using functions directly to sound note/turn off note/etc. I'll write my own routing for messages and post here so we might integrate into the lib later.

Thanks for the quick response!

**Comment by danigb** [comment]
Hi,

> It could be better if you just parsed/create the 3 byte standard MIDI messages in the library instead of using functions directly to sound note/turn off note/etc

I don't know what you mean, probably because I've never used the Web MIDI API. Can you elaborate a little bit?

>  I'll write my own routing for messages and post here so we might integrate into the lib later.

That would be great!

> Thanks for the quick response!

You're welcome :-)

**Comment by McOmghall** [comment]
> I don't know what you mean, probably because I've never used the Web MIDI API. Can you elaborate a little bit?

Well the MIDI api gives you midi inputs to which you can attach handlers for every MIDI event. These events usually have only standard MIDI messages that are 3 byte long (i.e. `[byte, byte, byte]` in javascript) and contain info like channel, action (note on, note off, switch instrument,...), note, velocity etc. Since this contains all the info you need to work with MIDI my guess is that you could base your library around only standard MIDI messages and make your functions like `instrument.play()` generate them and pass them to a standard MIDI interpreter.

Not entirely sure if this breaks your design though, it's just convenient to use

**Comment by danigb** [comment]
I don't know if I'm understanding you... What I suppose is that you want to attach a midi device to the computer and connect the MIDI messages it produces to soundfont library so when you play a key in the device, a note is played in the browser. If that's correct, maybe we could add something like `instrument.procMidiEvent` that handles an _input_ midi event and play or stops the player accordingly.

That sounds like a possible solution?

**Comment by McOmghall** [comment]
Yes that's exactly what I was trying to say.

**Comment by McOmghall** [comment]
Added a pull request. I'll let you manage review and npm publish.

**Comment by danigb** [comment]
Hi Pedro,

Thanks for the PR, and sorry for the response delay. I'm outside for a couple of days. I'll take a look to your PR when I'm back. Cheers, Dani

**Comment by McOmghall** [comment]
Since you're working on node you could just add `EventEmitter` as `require('events')` instead of rolling your own event emitter for `sample-player` just a reccm.
