### ISSUE TITLE
not working in Safari

### ISSUE THREAD

**Issue by hmoffatt** [danigb/soundfont-player#28]
I don't get any sound from the demos (either examples/index.html, nor the page at https://danigb.github.io/soundfont-player/ ) in Safari, either on the Mac or on iOS 9.3.2.

Firstly Safari uses the deprecated name webkitAudioContext. Once I changed that, I still don't get any sound from the soundfont-player page; it seems the soundfont loaded .then() promise is never called. I couldn't see why,

**Comment by danigb** [comment]
This is big! I'll take a look asap. Thanks!

**Comment by danigb** [comment]
Hi, I've updated marimba.js example to use webkitAudioContext and it works in my machine using OS X and Safari 9.0.2. Do you mind to test in your computer?

(You'll need beefy installed: `npm i -g beefy` and then `beefy examples/marimba.js` and open http://127.0.0.1:9966)

Thanks

**Comment by hmoffatt** [comment]
On 28/06/16 03:30, danigb wrote:
>
> Hi, I've updated marimba.js example to use webkitAudioContext and it 
> works in my machine using OS X and Safari 9.0.2. Do you mind to test 
> in your computer?
>
> (You'll need beefy installed: |npm i -g beefy| and then |beefy 
> examples/marimba.js| and open http://127.0.0.1:9966)
>
> Thanks
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/danigb/soundfont-player/issues/28#issuecomment-228815694>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/AHOeVHDKLtMsRWd0TnSe7iwH4H1DDrcpks5qQAiqgaJpZM4I-0No>.
>

Yes, that works for me now. Thanks.

I'd like to test it on iOS too, but Safari on iOS doesn't allow pages to 
automatically start playing, only on some user event like clicking a button.


By the way, I'm new to JS and NPM, but I think "npm install" is meant to 
install all the dependencies. However it's failing on web-audio-test-api 
(WeakMap ReferenceError)?


Hamish

**Comment by hmoffatt** [comment]
Here is a small demo patch to the marimba.js example so that it plays on 
click of a button, meaning it will make sound on iOS.

**Comment by smcnally** [comment]
Having this issue on iOS (Safari and Chrome) even with triggered sound events (vs onload).

Safari iOS error is 

`Can't find variable: AudioContext`

Installed beefy, but getting errors running `examples/marimba.js`

`Error: Could not find a suitable bundler!`

Happy to help troubleshoot MIDI and soundfont playing  on iOS vs my issues with beefy.

**Comment by laven2** [comment]
Up, i have similar problem in ios
> .then() promise is never called 
how to fix it?

**Comment by BoOz** [comment]
Hello,

I had sound in safari by adding first

```
	// AudioContext support
	var AudioContext = window.AudioContext // Default
	|| window.webkitAudioContext // Safari and old versions of Chrome
```

**Comment by danigb** [comment]
I think this issue is outside the scope of this project. Probably it would be nice to have a note about it in the README (PR is welcomed). 

I'll close the issue, but feel free to reopen in you think we should take some action from within the library.
