### ISSUE TITLE
crackles and performance issues on iOS

### ISSUE THREAD

**Issue by hmoffatt** [danigb/soundfont-player#29]
The marimba demo crackles on iOS after the first few notes start. You can hear the new notes starting slower too, until it catches up. I'm testing on an iPad mini (first generation).

I've noticed quite a lot of web audio applications behave this way especially on the older iPads. I think that the browser/CPU is not keeping up with the quantity of AudioBufferSourceNode nodes. I was able to make it work a bit better by 
1. adding a small start delay to all the notes
2. adding a duration property to each note that is played so that they don't overlap

I'm interested to know if anything can be done to improve performance. The marimba demo doesn't actually seem to max out the CPU unlike some of the others I've seen but it's still not keeping up.

Some other apps I've noticed crackling issues with are MIDI.js (webaudio output is unusable on iOS) (CPU > 100% all the time), and even this simple sound effects demo http://webaudioapi.com/samples/rapid-sounds/

**Comment by hmoffatt** [comment]
The iPad seems to splutter badly when there's more than about 18 AudioBufferSourceNodes. If I modify the marimba demo just to play 18 notes it is ok, beyond 20 it starts to crackle.

**Comment by danigb** [comment]
This is interesting... You mean 18 notes simultaneous? If so, we'll need a voice limit option (a feature I was thinking to implement some time ago...)

**Comment by hmoffatt** [comment]
I mean 18 notes scheduled, not even necessarily playing. I'm finding it a bit hard to characterise the issue. This code stutters (it's the original marimba.js demo code, except with 1 second delay added to the start):

```
    marimba.schedule(ac.currentTime, arr(36).map(function (_, i) {
      return { note: i + 60, time: i * 0.2 + 1 }
    }))
```

And this does too, even though none of the notes actually overlap:

```
    marimba.schedule(ac.currentTime, arr(36).map(function (_, i) {
      return { note: i + 60, time: i * 0.4 + 1, duration: 0.1, gain: 0.1 }
    }))
```

(even if you set the time to be 1 second between notes it's still bad).

This plays perfectly:

```
    marimba.schedule(ac.currentTime, arr(18).map(function (_, i) {
      return { note: i + 60, time: i * 0.2 + 1 }
    }))

```


Not only is there static and distortion but it seems like the notes are getting delayed. I can send a recording if that would be helpful. Changing the gain didn't help. 

It feels like there's a limit on how many AudioBufferSourceNodes can even exist at once (or are started), even if they haven't reached their start time yet.

I hacked on MIDI.js a bit to see if I could limit how many notes were scheduled in advance and it plays much better on my iPad now.

**Comment by danigb** [comment]
The first and last examples are the same, but change the number of notes, isn't it? So, it's seems to be a problem with the number of AudioBufferSourceNodes as you suggest... As I understand, this is a problem of iOS Safari, and I don't know what I can do about it... If you have any solution, is more than welcomed...

**Comment by hmoffatt** [comment]
Yes exactly, the third example works just by limiting the number of nodes. I don't see any solution at the soundfont-player layer; I think a higher layer scheduler would have to implement a limit and schedule new notes once earlier ones finish. By listening to your 'ended' event for example.

**Comment by hmoffatt** [comment]
Thanks for the discussion.
