### ISSUE TITLE
Duration ignored

### ISSUE THREAD

**Issue by wdenton** [danigb/soundfont-player#31]
I'm not sure if this is the same as #7 but the duration parameter has no effect when playing a note. In this example (I'm loading in sounds locally), changing the duration from 2 to 200 to 2000 does nothing. It always plays the MP3 once and that's it. 

````
      var ac = new AudioContext()
      Soundfont.instrument(ac, '/soundfont/cello-mp3.js').then(function (cello) {
        cello.play('C4', ac.currentTime, 2000)
      })
````

**Comment by danigb** [comment]
Hi,

The duration is expressed in seconds and samples are usually less than 2 seconds, so change from 2 to 200 to 2000 has no effect. Try smaller values like 0.2

I hope it helps.
Saludos,
Dani

**Comment by wdenton** [comment]
Thanks for the help---I guess I was right in thinking this was like #7, and there's no way to make sounds sustain.

But even with shorter times, the duration is still ignored, even though I think everything is configured properly. Here are three minimal examples, all the same except for the duration: [0.1 sec](http://ghg.earth/0.1.html), [0.5 sec](http://ghg.earth/0.5.html), [1.0 sec](http://ghg.earth/1.0.html). If the code there is right, why does the full reed organ sample always play?

**Comment by danigb** [comment]
Hi @wdenton,

sorry for the delay of the response, I'm on holidays. I'll be outside for a while, but I'll take a look to this issue when I'm back. Thanks!

**Comment by shahnizz** [comment]
Noticing the same thing as the OP. Just using the built in sounds. Seems to play the same full length of the sample no matter what the third param is.

```
 var ac = new AudioContext();
 Soundfont.instrument(ac, 'acoustic_grand_piano').then((piano)=>{
          piano.play(75, ac.currentTime, .1);
 })
```

**Comment by danigb** [comment]
Hi, 

Now I had time to look at this, I can see it's a problem of documentation. The way to do this is:

```js
piano.play(75, ac.currentTime, { duration: 0.1})
```
I'll update the documentation. Please, tell me if that works for you.

**Comment by danigb** [comment]
I think this issue is now solved. Please feel free to reopen if doesn't work for you.
Regards,
Dani
