### ISSUE TITLE
Gain:0 should be off?

### ISSUE THREAD

**Issue by grimmdude** [danigb/soundfont-player#35]
Hey man, great library.  Both you and I seem to be interested in programming and music.  I'm working on a MIDI player and am using this library for the sounds.  I find that when I set `gain` to `0` the note still sounds.  Would be be possible for the note to be silent in that case?

Here's the MIDI player I'm working on: http://grimmdude.com/MidiPlayerJS/

Thanks,
Garrett

**Comment by danigb** [comment]
Hi Garret,

Yes, I've seen your before in some music related repo discussion. The midi player project looks great! Congrats.

And yes, `{ gain: 0 }` should be silent sounds. If not, is a bug. I'll take a look shortly.

Thanks,
Dani

**Comment by danigb** [comment]
Hi @grimmdude, 

I think this is fixed. Please feel free to reopen if doesn't work to you.
Regards,
Dani

**Comment by grimmdude** [comment]
I'm not sure if it's related, but after these changes it seems that now sounds are not working at all and I'm seeing a bunch of these errors:

Buffer E6 not found.

I'm using `dist/soundfont-player.min.js` from master branch and loading the soundfont from https://raw.githubusercontent.com/gleitz/midi-js-soundfonts/gh-pages/MusyngKite/clavichord-mp3.js  

Reverting  back to `dist/soundfont-player.min.js` before this change works fine. 

-Garrett

**Comment by danigb** [comment]
Hi Garrett,

It's weird, the local examples works on my machine with the last changes... I'll take a look to it. Sorry for the inconvenience.

Saludos

**Comment by danigb** [comment]
Hi @grimmdude 

I think I've fix the issue. Do you mind to test using the distribution file from master
Thanks

**Comment by grimmdude** [comment]
Yes looks like that fixed it, thanks!

**Comment by danigb** [comment]
Hi Garret, thanks for checking 👍
