### ISSUE TITLE
play().stop() does not work

### ISSUE THREAD

**Issue by cpansprout** [danigb/soundfont-player#36]
Your main readme file says I can do this:
```
  // or stop only one
  clavinet.play('C4').stop(ac.currentTime + 0.5)
```
but it doesn’t work, because play(), an alias for start(), does not return start()’s return value.

Changing
```
  player.play = function (n, w, o) { player.start(n, w, o) }
```
to
```
  player.play = function (n, w, o) { return player.start(n, w, o) }
```
makes it work.

I tried to file a pull request, but it’s not showing up.  In any case, it had a mistake in it, in that it stopped microtones from working, so if the pull request does show up at some point it should be discarded.

**Comment by danigb** [comment]
Good catch! I'll address it shortly.
Thanks

**Comment by danigb** [comment]
Please feel free to reopen if doesn't work to you.
Regards,
Dani

**Comment by cpansprout** [comment]
Unfortunately, it causes microtones to stop working.  It seems (I don’t fully understand your code) that player.start gets redefined at some point (I see two instances of `player.start =` in the code), so player.play does need to remain a wrapper.  It just needs to return the value that player.start returns.  Alternatively, whichever code is redefining player.start could also redefine player.play at the same time.

**Comment by danigb** [comment]
Ok. I'll take a look. Thanks, @cpansprout

**Comment by danigb** [comment]
Hi @cpansprout, I think I've fixed the issue. Do you mind to test it against master branch?
Thanks.

**Comment by cpansprout** [comment]
Yes, I have tested it and it works.  Thank you.

**Comment by danigb** [comment]
Thanks!!
