### ISSUE TITLE
‘Buffer null not found.’

### ISSUE THREAD

**Issue by cpansprout** [danigb/soundfont-player#38]
This may be related to #28.  The player is not working in Safari, but only on some machines.

The console contains the message ‘Buffer null not found’.  What can I do to help debug this?

**Comment by danigb** [comment]
I would need more information to solve the issue. At least, the code you are using related to soundfont-player. Also, remember that in Safari you need to create the audio context different.

**Comment by cpansprout** [comment]
Yes, I am doing `new (window.AudioContext || webkitAudioContext)`.  You can see the full code at https://gist.github.com/cpansprout/fc23a110656cabda8abb32de13ac2c46#file-byzsynth-html (sans graphics).

**Comment by danigb** [comment]
Great! It would be nice to know what buffer are you asking for to know why it's missing. I made a comment in your gist.

**Comment by cpansprout** [comment]
How stupid of me! In Firefox the numbers I am getting are 48, 50, 51.666666666666664, 53, which I would expect. In Safari I am getting NaN, so the problem appears to be in my code, not yours. Thank you for pointing me in the right direction. :-)

(The problem was that radio button node lists have no .value property in Safari, as they do in Firefox and Chrome. Sorry for the noise.)
