### ISSUE TITLE
Play midi file inside arraybuffer.

### ISSUE THREAD

**Issue by redbrain** [danigb/soundfont-player#4]
I have wrote code which encodes Doom's Mus into Midi and cannot find a method to play this inside javascript in a clean and simple way. Can this take an array buffer of midi data?

**Comment by danigb** [comment]
I'm afraid not, this library is only to load and make sound with json encoded soundfont files. Probably https://github.com/mudcube/MIDI.js/ can do the job (but maybe there are newer libraries).

Saludos
