### ISSUE TITLE
Player scheduler - register a callback to be invoked when note is played

### ISSUE THREAD

**Issue by steinfletcher** [danigb/soundfont-player#41]
This is a great little library, many thanks.

I would like to know if it's possible to register a function to be invoked when the scheduler plays each note. My use case is that I want to animate a UI element when each note plays.

Is this possible? If not, how might I go about implementing it?

**Comment by danigb** [comment]
Hi @steinfletcher 

The scheduler included with soundfont-player is really basic, and no callback is called. I'm afraid you should use something more sophisticated. Here are some options:

- https://github.com/sebpiq/WAAClock
- https://github.com/soundio/clock
- https://github.com/mmckegg/bopper
- https://github.com/Tonejs/Tone.js/

The one I like most is Tone.js but the library is huge. Apart of this, the only one I've tried is WAAClock.

Hope it helps

**Comment by steinfletcher** [comment]
Many thanks @danigb. Closing this
