### ISSUE TITLE
Using .sf2 files

### ISSUE THREAD

**Issue by Fluxionsdx** [danigb/soundfont-player#42]
I am trying to use samples from a .sf2 file that I downloaded from http://www.flamestudios.org/free/Soundfonts.
I am serving the file from my server and trying to call it like this:
Soundfont.instrument(this.fbs.audioContext, "IBNZSteelString.sf2", { from: 'http://localhost:3000/' }).then((instrument)=> {this.fbs.instrument = instrument;})

I'm getting the following error in the console: https://gleitz.github.io/midi-js-soundfonts/MusyngKite/IBNZSteelString.sf2-mp3.js  404 Not Found. It doesn't look like soundfont-player is making the call to my server, but rather to the default gleitz github.

What am I doing wrong?

**Comment by danigb** [comment]
Hi,

this library only works with pre-rendered soundfont files. You can pre-render with https://github.com/PatrickWolleb/SoundFontJS or search github for another library that can use them directly (I know it exists, but I could not remember the name).

Hope it helps.
Good luck

**Comment by Fluxionsdx** [comment]
Awesome, thank you.
