### ISSUE TITLE
need to update copy of MusyngKite's name.json

### ISSUE THREAD

**Issue by kirlen** [danigb/soundfont-player#48]
instrument names were changed in gleitz' repo on 6/11, causing 404's for multiple instruments, e.g. https://gleitz.github.io/midi-js-soundfonts/MusyngKite/synthbrass_1-mp3.js
(should now be https://gleitz.github.io/midi-js-soundfonts/MusyngKite/synth_brass_1-mp3.js)

See: https://github.com/gleitz/midi-js-soundfonts/commits/gh-pages/MusyngKite/names.json

**Comment by danigb** [comment]
Hi @kirlen,

thanks for reporting :+1:  Is your #48 PR a fix of this issue? If so, can we close this issue?

Regards,
Dani

**Comment by kirlen** [comment]
Hi,
Yes it's a fix -- the one thing i forgot to do was bump the package version -- which I've submitted another PR for. Not sure if version bump triggers availability on NPM, but that's what I'm hoping :)

**Comment by danigb** [comment]
I've published the last version to NPM. Thanks! 👍
