### ISSUE TITLE
loading Soundfont player

### ISSUE THREAD

**Issue by Treefrog74** [danigb/soundfont-player#70]
Hello - 
Please forgive my ignorance as I am relatively new to programming. 

I am using the Soundfont player for a sketch in p5.js. I have created a play button to play my song after I have chosen my instruments. If I press the play button right away, the sound is a bit choppy. If I wait a second or two, it's fine. Is there a simple line I can add that will prevent the song from playing until the sound is fully loaded? 
i.e. if (instrument.isLoaded()){instrument.play}
Thanks

**Comment by danigb** [comment]
Hi @Treefrog74 

I don't know what exactly can be the cause of your problem. In theory, if you write this:
```js
Soundfont.instrument(new AudioContext(), 'acoustic_grand_piano').then(function (piano) {
  // 👉 at this point the piano is fully loaded
  piano.play('C4')
})
```

Nowadays, starting audio context is a little bit tricky. I think your problem could be related to that: https://developers.google.com/web/updates/2017/09/autoplay-policy-changes

If so, this may help: https://github.com/JohnWeisz/web-audio-api-autostart

hope it works! good luck 🤞

**Comment by Treefrog74** [comment]
Thanks for responding! I really appreciate it.

I will look a little deeper with your suggestions. If I can’t get it working I’ll send you a link to the sketch I’m working on.

Leo
