### ISSUE TITLE
Loading instruments via `require` or other compile-time means

### ISSUE THREAD

**Issue by artsyca** [danigb/soundfont-player#84]
I'd like to include my instrument files in the application bundle using webpack or some other means to save an HTTP request on the client side and the requisite ajax call. Is there the possibility loading the soundfont instruments using an `import` or other similar method?

**Comment by VadeanAndrada** [comment]
Any updates on this? Thank you!

**Comment by artsyca** [comment]
I think we just used the assets via http request.
